server:
  port: 8081
spadas:
  dimension: 2
  resolution: 10
  leaf-capacity: 1000
  cache-dataset: false
  cache-index: true
  save-index: false
  frontend-limitation: 10000
  file:
    baseUri: ./dataset/
    staticUri: /dataset/
