spadas:
  dimension: 2
  resolution: 10
  leaf-capacity: 1000
  cache-dataset: true
  cache-index: true
  save-index: true
  frontend-limitation: 10000
  default-roadmap: Pittsburgh
  file:
    baseUri: ./dataset-mini/
    staticUri: /dataset-mini/
