env:
  name: 'dev'
name: Deploy on Dev
on:
  push:
    branches:
      - dev
jobs:
  deploy:
    name: integrate with maven
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Maven Package
        run: mvn package -DskipTests=true

      - name: Upload Package
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.HOST }}
          port: ${{ secrets.FTP_PORT }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          local-dir: 'target/'
          server-dir: 'spadas/'

      - name: Deploy On Server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          command_timeout: 1m
          script: |
            echo "ok!" > test.txt
